// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/usuario/Documents/Proyecto_prototipo_Funtempo/Funtempo/Funtempo_Frontend/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/usuario/Documents/Proyecto_prototipo_Funtempo/Funtempo/Funtempo_Frontend/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('Funtempo', appParameters);
});
require('c:/Users/usuario/Documents/Proyecto_prototipo_Funtempo/Funtempo/Funtempo_Frontend/index.android.js');